using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class EnvSyncModel
{
    [RealtimeProperty(1, true, true)]
    private bool _sphereEnabled;
    [RealtimeProperty(2, true, true)]
    private bool _particlesEnabled;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class EnvSyncModel : RealtimeModel {
    public bool sphereEnabled {
        get {
            return _sphereEnabledProperty.value;
        }
        set {
            if (_sphereEnabledProperty.value == value) return;
            _sphereEnabledProperty.value = value;
            InvalidateReliableLength();
            FireSphereEnabledDidChange(value);
        }
    }
    
    public bool particlesEnabled {
        get {
            return _particlesEnabledProperty.value;
        }
        set {
            if (_particlesEnabledProperty.value == value) return;
            _particlesEnabledProperty.value = value;
            InvalidateReliableLength();
            FireParticlesEnabledDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(EnvSyncModel model, T value);
    public event PropertyChangedHandler<bool> sphereEnabledDidChange;
    public event PropertyChangedHandler<bool> particlesEnabledDidChange;
    
    public enum PropertyID : uint {
        SphereEnabled = 1,
        ParticlesEnabled = 2,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _sphereEnabledProperty;
    
    private ReliableProperty<bool> _particlesEnabledProperty;
    
    #endregion
    
    public EnvSyncModel() : base(null) {
        _sphereEnabledProperty = new ReliableProperty<bool>(1, _sphereEnabled);
        _particlesEnabledProperty = new ReliableProperty<bool>(2, _particlesEnabled);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _sphereEnabledProperty.UnsubscribeCallback();
        _particlesEnabledProperty.UnsubscribeCallback();
    }
    
    private void FireSphereEnabledDidChange(bool value) {
        try {
            sphereEnabledDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireParticlesEnabledDidChange(bool value) {
        try {
            particlesEnabledDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _sphereEnabledProperty.WriteLength(context);
        length += _particlesEnabledProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _sphereEnabledProperty.Write(stream, context);
        writes |= _particlesEnabledProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.SphereEnabled: {
                    changed = _sphereEnabledProperty.Read(stream, context);
                    if (changed) FireSphereEnabledDidChange(sphereEnabled);
                    break;
                }
                case (uint) PropertyID.ParticlesEnabled: {
                    changed = _particlesEnabledProperty.Read(stream, context);
                    if (changed) FireParticlesEnabledDidChange(particlesEnabled);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _sphereEnabled = sphereEnabled;
        _particlesEnabled = particlesEnabled;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
