using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PanelSyncModel
{
    [RealtimeProperty(1, true, true)] // Panel content type (0 = video, 1 = image, 2 = image series)
    private int _contentType;
    [RealtimeProperty(2, true, true)]
    private int _contentIndex;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PanelSyncModel : RealtimeModel {
    public int contentType {
        get {
            return _contentTypeProperty.value;
        }
        set {
            if (_contentTypeProperty.value == value) return;
            _contentTypeProperty.value = value;
            InvalidateReliableLength();
            FireContentTypeDidChange(value);
        }
    }
    
    public int contentIndex {
        get {
            return _contentIndexProperty.value;
        }
        set {
            if (_contentIndexProperty.value == value) return;
            _contentIndexProperty.value = value;
            InvalidateReliableLength();
            FireContentIndexDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PanelSyncModel model, T value);
    public event PropertyChangedHandler<int> contentTypeDidChange;
    public event PropertyChangedHandler<int> contentIndexDidChange;
    
    public enum PropertyID : uint {
        ContentType = 1,
        ContentIndex = 2,
    }
    
    #region Properties
    
    private ReliableProperty<int> _contentTypeProperty;
    
    private ReliableProperty<int> _contentIndexProperty;
    
    #endregion
    
    public PanelSyncModel() : base(null) {
        _contentTypeProperty = new ReliableProperty<int>(1, _contentType);
        _contentIndexProperty = new ReliableProperty<int>(2, _contentIndex);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _contentTypeProperty.UnsubscribeCallback();
        _contentIndexProperty.UnsubscribeCallback();
    }
    
    private void FireContentTypeDidChange(int value) {
        try {
            contentTypeDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    private void FireContentIndexDidChange(int value) {
        try {
            contentIndexDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _contentTypeProperty.WriteLength(context);
        length += _contentIndexProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _contentTypeProperty.Write(stream, context);
        writes |= _contentIndexProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.ContentType: {
                    changed = _contentTypeProperty.Read(stream, context);
                    if (changed) FireContentTypeDidChange(contentType);
                    break;
                }
                case (uint) PropertyID.ContentIndex: {
                    changed = _contentIndexProperty.Read(stream, context);
                    if (changed) FireContentIndexDidChange(contentIndex);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _contentType = contentType;
        _contentIndex = contentIndex;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
